name: format_nwk_tree
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11.4
  - pip:
    - ete3==3.1.3
    - git+https://github.com/jeetsukumaran/DendroPy.git@26c3bfba473ddee5db2856c79b7f22702ce903e1#egg=DendroPy
    - six==1.16.0
    - numpy==1.25.1
